### ISSUE TITLE
Use logger instead of printing stack trace for caught exceptions

### ISSUE THREAD

**Issue by LucaScorpion** [LucaScorpion/JavaRant#12]

**Comment by tahnik** [comment]
Hey @LucaScorpion, can we prioritize this? It is becoming really hard to trace other exception because the API is also printing trace.

Thank you

**Comment by LucaScorpion** [comment]
@tahnik Sure, I'll try to get some other stuff in there as well and deploy a new version by tonight.

**Comment by LucaScorpion** [comment]
Fixed in v1.3
