### ISSUE TITLE
Research method return values

### ISSUE THREAD

**Issue by LucaScorpion** [LucaScorpion/JavaRant#6]
Right now when a method can't get rants (or collabs, etc) it returns null. ~~These methods should be changed to return an optional.~~ It should be researched whether this is the best option. Other options are:

- Return an empty list (for methods that return a list)
- Don't catch the exceptions, or throw a custom one
- Return an optional

**Comment by tahnik** [comment]
I am not sure if you should do this yet. Optional are used for nested objects as far as I know. It might be worth doing a a full research on it before implementing it.

**Comment by LucaScorpion** [comment]
@tahnik Good point, it was more something for later on but it should indeed be researched first.

**Comment by LucaScorpion** [comment]
Obsolete issue as this has been completely reworked for version 2.
